/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
-- book status seed
INSERT INTO [dbo].[BookReservationStatus]([BookReservationStatusName])VALUES('Pending')
INSERT INTO [dbo].[BookReservationStatus]([BookReservationStatusName])VALUES('Reserved')
INSERT INTO [dbo].[BookReservationStatus]([BookReservationStatusName])VALUES('Returned')
INSERT INTO [dbo].[BookReservationStatus]([BookReservationStatusName])VALUES('Canceled')

--- book seed
INSERT INTO [dbo].[Book]([BookName],[BookDescription],[Quantity], [Booked], [AuthorName])VALUES('The Girl with the Dragon Tattoo', 'Disgraced financial reporter Mikael Blomkvist (Daniel Craig) finds a chance to redeem his honor after being hired by wealthy Swedish industrialist Henrik Vanger (Christopher Plummer) to solve the 40-year-old murder of Vanger''s niece, Harriet.', 5, 0,'Stieg Larsson')
INSERT INTO [dbo].[Book]([BookName],[BookDescription],[Quantity], [Booked], [AuthorName])VALUES('The Girl Who Played with Fire', 'Mikael Blomkvist, crusading publisher of the magazine Millennium, has decided to run a story that will expose an extensive sex trafficking operation. On the eve of its publication, the two reporters responsible for the article are murdered, and the fingerprints found on the murder weapon belong to his friend, the troubled genius hacker Lisbeth Salander. Blomkvist, convinced of Salander’s innocence, plunges into an investigation. Meanwhile, Salander herself is drawn into a murderous game of cat and mouse, which forces her to face her dark past.', 3, 0,'Stieg Larsson')
INSERT INTO [dbo].[Book]([BookName],[BookDescription],[Quantity], [Booked], [AuthorName])VALUES('The Girl Who Kicked the Hornets'' Nest', 'Lisbeth Salander - the heart of Larsson''s two previous novels - lies in critical condition, a bullet wound to her head, in the intensive care unit of a Swedish city hospital. She''s fighting for her life in more ways than one: if and when she recovers, she''ll be taken back to Stockholm to stand trial for three murders. With the help of her friend, journalist Mikael Blomkvist, she will not only have to prove her innocence, but also identify and denounce those in authority who have allowed the vulnerable, like herself, to suffer abuse and violence. And, on her own, she will plot revenge - against the man who tried to kill her, and the corrupt government institutions that very nearly destroyed her life.', 2, 0, 'Stieg Larsson')
INSERT INTO [dbo].[Book]([BookName],[BookDescription],[Quantity], [Booked], [AuthorName])VALUES('In Search of Lost Time', 'Swann''s Way, the first part of A la recherche de temps perdu, Marcel Proust''s seven-part cycle, was published in 1913. In it, Proust introduces the themes that run through the entire work. The narrator recalls his childhood, aided by the famous madeleine; and describes M. Swann''s passion for Odette. The work is incomparable. Edmund Wilson said "[Proust] has supplied for the first time in literature an equivalent in the full scale for the new theory of modern physics.', 5, 0, 'Marcel Proust')
INSERT INTO [dbo].[Book]([BookName],[BookDescription],[Quantity], [Booked], [AuthorName])VALUES('Don Quixote', 'Alonso Quixano, a retired country gentleman in his fifties, lives in an unnamed section of La Mancha with his niece and a housekeeper. He has become obsessed with books of chivalry, and believes their every word to be true, despite the fact that many of the events in them are clearly impossible. Quixano eventually appears to other people to have lost his mind from little sleep and food and because of so much reading.', 7, 0, 'Miguel de Cervantes')
INSERT INTO [dbo].[Book]([BookName],[BookDescription],[Quantity], [Booked], [AuthorName])VALUES('Ulysses', 'Ulysses chronicles the passage of Leopold Bloom through Dublin during an ordinary day, June 16, 1904. The title parallels and alludes to Odysseus (Latinised into Ulysses), the hero of Homer''s Odyssey (e.g., the correspondences between Leopold Bloom and Odysseus, Molly Bloom and Penelope, and Stephen Dedalus and Telemachus). Joyce fans worldwide now celebrate June 16 as Bloomsday.', 4, 0, 'James Joyce')
INSERT INTO [dbo].[Book]([BookName],[BookDescription],[Quantity], [Booked], [AuthorName])VALUES('The Great Gatsby', 'The novel chronicles an era that Fitzgerald himself dubbed the "Jazz Age". Following the shock and chaos of World War I, American society enjoyed unprecedented levels of prosperity during the "roaring" 1920s as the economy soared. At the same time, Prohibition, the ban on the sale and manufacture of alcohol as mandated by the Eighteenth Amendment, made millionaires out of bootleggers and led to an increase in organized crime, for example the Jewish mafia.Although Fitzgerald, like Nick Carraway in his novel, idolized the riches and glamor of the age, he was uncomfortable with the unrestrained materialism and the lack of morality that went with it, a kind of decadence.', 5, 0, 'F. Scott Fitzgerald')
INSERT INTO [dbo].[Book]([BookName],[BookDescription],[Quantity], [Booked], [AuthorName])VALUES('Moby Dick', 'First published in 1851, Melville''s masterpiece is, in Elizabeth Hardwick''s words, "the greatest novel in American literature." The saga of Captain Ahab and his monomaniacal pursuit of the white whale remains a peerless adventure story but one full of mythic grandeur, poetic majesty, and symbolic power. Filtered through the consciousness of the novel''s narrator, Ishmael, Moby-Dick draws us into a universe full of fascinating characters and stories, from the noble cannibal Queequeg to the natural history of whales, while reaching existential depths that excite debate and contemplation to this day.', 2, 0, 'Herman Melville')
INSERT INTO [dbo].[Book]([BookName],[BookDescription],[Quantity], [Booked], [AuthorName])VALUES('Hamlet', 'The Tragedy of Hamlet, Prince of Denmark, or more simply Hamlet, is a tragedy by William Shakespeare, believed to have been written between 1599 and 1601. The play, set in Denmark, recounts how Prince Hamlet exacts revenge on his uncle Claudius, who has murdered Hamlet''s father, the King, and then taken the throne and married Gertrude, Hamlet''s mother. The play vividly charts the course of real and feigned madness—from overwhelming grief to seething rage—and explores themes of treachery, revenge, incest, and moral corruption.', 10, 0, 'William Shakespeare')
INSERT INTO [dbo].[Book]([BookName],[BookDescription],[Quantity], [Booked], [AuthorName])VALUES('War and Peace', 'Epic in scale, War and Peace delineates in graphic detail events leading up to Napoleon''s invasion of Russia, and the impact of the Napoleonic era on Tsarist society, as seen through the eyes of five Russian aristocratic families.', 3, 0, 'Leo Tolstoy')
INSERT INTO [dbo].[Book]([BookName],[BookDescription],[Quantity], [Booked], [AuthorName])VALUES('The Odyssey', 'The Odyssey is one of two major ancient Greek epic poems attributed to Homer. It is, in part, a sequel to the Iliad, the other work traditionally ascribed to Homer. The poem is fundamental to the modern Western canon. Indeed it is the second—the Iliad being the first—extant work of Western literature. It was probably composed near the end of the eighth century BC, somewhere in Ionia, the Greek-speaking coastal region of what is now Turkey. The poem mainly centers on the Greek hero Odysseus (or Ulysses, as he was known in Roman myths) and his long journey home following the fall of Troy. It takes Odysseus ten years to reach Ithaca after the ten-year Trojan War. In his absence, it is assumed he has died, and his wife Penelope and son Telemachus must deal with a group of unruly suitors, the Mnesteres or Proci, competing for Penelope''s hand in marriage.', 6, 0, 'Homer')
INSERT INTO [dbo].[Book]([BookName],[BookDescription],[Quantity], [Booked], [AuthorName])VALUES('One Hundred Years of Solitude', 'One of the 20th century''s enduring works, One Hundred Years of Solitude is a widely beloved and acclaimed novel known throughout the world, and the ultimate achievement in a Nobel Prize–winning career. The novel tells the story of the rise and fall of the mythical town of Macondo through the history of the Buendía family. It is a rich and brilliant chronicle of life and death, and the tragicomedy of humankind. In the noble, ridiculous, beautiful, and tawdry story of the Buendía family, one sees all of humanity, just as in the history, myths, growth, and decay of Macondo, one sees all of Latin America. Love and lust, war and revolution, riches and poverty, youth and senility — the variety of life, the endlessness of death, the search for peace and truth — these universal themes dominate the novel. Whether he is describing an affair of passion or the voracity of capitalism and the corruption of government, Gabriel García Márquez always writes with the simplicity, ease, andpurity that are the mark of a master. Alternately reverential and comical, One Hundred Years of Solitude weaves the political, personal, and spiritual to bring a new consciousness to storytelling. Translated into dozens of languages, this stunning work is no less than an accounting of the history of the human race.', 2, 0, 'Gabriel Garcia Marquez')
INSERT INTO [dbo].[Book]([BookName],[BookDescription],[Quantity], [Booked], [AuthorName])VALUES('The Brothers Karamazov', 'Dostoevsky''s last and greatest novel, The Karamazov Brothers, is both a brilliantly told crime story and a passionate philosophical debate. The dissolute landowner Fyodor Pavlovich Karamazov is murdered; his sons — the atheist intellectual Ivan, the hot-blooded Dmitry, and the saintly novice Alyosha — are all at some level involved. Bound up with this intense family drama is Dostoevsky''s exploration of many deeply felt ideas about the existence of God, the question of human freedom, the collective nature of guilt, the disastrous consequences of rationalism. The novel is also richly comic: the Russian Orthodox Church, the legal system, and even the author''s most cherished causes and beliefs are presented with a note of irreverence, so that orthodoxy and radicalism, sanity and madness, love and hatred, right and wrong are no longer mutually exclusive. Rebecca West considered it "the allegory for the world''s maturity, but with children to the fore." This new translation does full justice to Dostoevsky''s genius, particularly in the use of the spoken word, which ranges over every mode of human expression.', 2, 0, 'Fyodor Dostoyevsky')
INSERT INTO [dbo].[Book]([BookName],[BookDescription],[Quantity], [Booked], [AuthorName])VALUES('Madame Bovary', 'For daring to peer into the heart of an adulteress and enumerate its contents with profound dispassion, the author of Madame Bovary was tried for "offenses against morality and religion." What shocks us today about Flaubert''s devastatingly realized tale of a young woman destroyed by the reckless pursuit of her romantic dreams is its pure artistry: the poise of its narrative structure, the opulence of its prose (marvelously captured in the English translation of Francis Steegmuller), and its creation of a world whose minor figures are as vital as its doomed heroine. In reading Madame Bovary, one experiences a work that remains genuinely revolutionary almost a century and a half after its creation.', 4, 0, 'Gustave Flaubert')